name: mtt
description: Minetest test runner
inputs:
  modname:
    description: "manual modname to use (if no mod.conf provided)"
    required: false
    default: "testmod"
  dependencies:
    description: "list of dependencies to download"
    required: false
    default: ""
#  engine_image:
#    description: minetest engine docker image
#    required: false
#    default: "registry.gitlab.com/minetest/minetest/server:5.6.0"
runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: check-square
  color: yellow