name: mtt
description: Minetest test runner
inputs:
  modname:
    description: "the modname to test"
    required: true
  dependencies:
    description: "list of dependencies to download"
    required: false
    default: "https://github.com/BuckarooBanzay/mtt"
  additional_config:
    description: "additional lines for minetest.conf"
    required: false
    default: ""

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: check
  color: yellow