name: mtt-runner
description: Minetest test runner
inputs:
  modname:
    description: "the modname to test, defaults to the repository name"
    required: false
    default: ""
  mtt_filter:
    description: "list of mods to test, defaults to the modname"
    required: false
    default: ""
  git_dependencies:
    description: "list of git-dependencies to download"
    required: false
    default: "https://github.com/BuckarooBanzay/mtt"
  additional_config:
    description: "additional lines for minetest.conf"
    required: false
    default: ""
  git_game_repo:
    description: "git repo of the game to use"
    required: false
    default: "https://github.com/minetest/minetest_game"
  test_mode:
    description: "testing mode, either 'mod' or 'game'"
    required: false
    default: "mod"
  mapgen:
    description: "mapgen name"
    required: false
    default: "singlenode"
  enable_coverage:
    description: "enable lua code coverage"
    required: false
    default: "false"
  enable_benchmarks:
    description: "enable benchmarks"
    required: false
    default: "false"

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: check
  color: yellow