name: mtt
description: Minetest test runner
#inputs:
#  engine_image:
#    description: minetest engine docker image
#    required: false
#    default: "registry.gitlab.com/minetest/minetest/server:5.6.0"
runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: check-square
  color: yellow