version: "3.6"

services:
 sut:
  build:
   context: ./test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.5.0}
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/mtt/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"
    - "./coverage:/var/lib/minetest"

volumes:
  world: {}