version: "3.6"

services:
 sut:
  build:
   context: ./test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.5.0}
  environment:
    COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
    COVERALLS_DEBUG: "true"
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/mtt/"
    - "./test/mod:/root/.minetest/worlds/world/worldmods/test_mod/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"

volumes:
  world: {}