name: coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        luarocks install luacov-coveralls
        docker-compose up --exit-code-from sut
        id
        docker cp mtt_sut_1:/root/.minetest ./root/
        luacov-coveralls -v
