name: coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install -y luarocks
        sudo luarocks install luacov-coveralls
        docker-compose up --exit-code-from sut
        sudo docker cp mtt_sut_1:/root/.minetest ./root/
        sudo docker cp mtt_sut_1:/var/lib/minetest/luacov.stats.out .
        luacov-coveralls -v
