name: test-action

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./action.yml
      with:
        modname: mtt
        enable_coverage: "true"
        enable_benchmarks: true
        git_dependencies: |
          https://github.com/BuckarooBanzay/promise
        additional_config: |
          mtt_enable_selftest = true
